#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["package-once-blue", "blue"]
#
# [tool.uv.sources]
# package-once-blue = { git = "https://github.com/getcolors/once.git", rev = "76db60cfc43ee49b2a214ea2819642f64f1a8e6c", subdirectory = "blue" }
# blue = { git = "https://github.com/getcolors/blue.git", rev = "7dd17ac920060f622f9f98b503bbe36e35d730ec" }
# ///
"""Thin launcher for package-once-blue."""
from package_once_blue import exec, run

__all__ = ["run"]

if __name__ == "__main__":
    exec()
